pipeline:

  test:
    image: ownport/eventsflow-dev:0.1.2-ubuntu  
    commands:
    - make pre-cleanup
    - pip3 install -e .
    - PYTHONDONTWRITEBYTECODE=1 pytest 
        --cov=eventsflow 
        -p no:cacheprovider 
        --junitxml=report.xml 
        --cov-report=term-missing 
        --cov-config=.coveragerc
    - make post-cleanup
    when:
      event: 
      - test
      # - release
  
  release:
    image: ownport/eventsflow-dev:0.1.2-ubuntu  
    commands:
    - make pre-cleanup
    - bumpversion part --tag
    - twine upload dist/*
    # - bumpversion --serialize {major}.{minor}.{patch}.dev0 patch
    - make post-clean
    when:
      event: 
      - release

