default:
  image: registry.gitlab.com/eventsflow/docker/dev:0.6.0-ubuntu

stages:
- test
- release
- build
- deploy

test_eventflow:
  stage: test
  script:
  - /usr/sbin/dev/run-pytests.sh
  artifacts:
    reports:
      junit: report.xml

release_eventflow:
  stage: release
  script:
  - echo "[WARNING] Not implemented yet"
  only:
  - tags

build_eventflow:
  stage: build
  script:
  - python3 setup.py sdist bdist_wheel
  artifacts:
    paths:
    - dist/*.whl
    - dist/*.tar.gz
    expire_in: 5 mins
  only:
  - tags

deploy_eventflow:
  stage: deploy
  script:
  - >
    TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token 
    python3 -m twine upload 
    --repository-url https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi
    dist/*
  only:
  - tags
