default:
  image: registry.gitlab.com/eventsflow/docker/dev:0.5.4-ubuntu

variables:


stages:
- build
- test
- release

test_eventflow:
  stage: test
  script:
  - /usr/sbin/dev/run-pytests.sh
  artifacts:
    reports:
      junit: report.xml
